import React, { useRef } from 'react';
import { motion } from 'framer-motion';
import { Doughnut } from 'react-chartjs-2';
import { jsPDF } from 'jspdf';
import { Chart as ChartJS, ArcElement, Tooltip, Legend } from 'chart.js';
import { Download, AlertTriangle, CheckCircle, Clock, Layers, FileText, Shield } from 'lucide-react';

ChartJS.register(ArcElement, Tooltip, Legend);

const ResultsSection = ({ result }) => {
    if (!result) return null;

    const { score, timeTaken, matches, rangesB, suspectText } = result;

    // Chart Config with cybersecurity theme
    const chartData = {
        labels: ['Similarity', 'Unique'],
        datasets: [{
            data: [score, 100 - score],
            backgroundColor: [
                score > 50 ? 'rgba(239, 68, 68, 0.8)' : 'rgba(6, 182, 212, 0.8)',
                'rgba(30, 41, 59, 0.3)'
            ],
            borderColor: [
                score > 50 ? 'rgba(239, 68, 68, 1)' : 'rgba(6, 182, 212, 1)',
                'transparent'
            ],
            borderWidth: 2,
        }],
    };

    const chartOptions = {
        responsive: true,
        maintainAspectRatio: false,
        plugins: { legend: { display: false }, tooltip: { enabled: false } },
        cutout: '75%',
        events: []
    };

    const renderHighlightedContent = () => {
        if (score === 0) return (
            <div className="text-center py-12">
                <CheckCircle size={48} className="text-primary mx-auto mb-4" />
                <p className="text-muted-foreground">No significant overlaps detected.</p>
                <p className="text-sm text-muted-foreground/60 mt-2">Content appears to be original</p>
            </div>
        );

        const STOP_WORDS = new Set([
            'a', 'an', 'the', 'and', 'or', 'but', 'if', 'because', 'as', 'what',
            'when', 'where', 'how', 'who', 'which', 'this', 'that', 'these', 'those',
            'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had',
            'do', 'does', 'did', 'at', 'by', 'for', 'from', 'in', 'of', 'on', 'to',
            'with', 'about', 'can', 'could', 'will', 'would', 'should'
        ]);

        const tokens = suspectText
            .toLowerCase()
            .replace(/[^\w\s]/g, '')
            .replace(/\s+/g, ' ')
            .trim()
            .split(' ')
            .filter(word => !STOP_WORDS.has(word) && word.length > 0);

        const highlightedIndices = new Set();
        rangesB.forEach(([start, end]) => {
            for (let i = start; i <= end; i++) highlightedIndices.add(i);
        });

        return (
            <div className="bg-secondary/30 p-6 rounded-xl leading-relaxed text-foreground font-mono text-sm border border-border/50 max-h-[400px] overflow-y-auto backdrop-blur-sm">
                {tokens.map((token, index) => (
                    <span
                        key={index}
                        className={highlightedIndices.has(index) 
                            ? 'bg-red-500/20 text-red-400 border-b-2 border-red-500 mx-0.5 px-1 rounded-t-sm animate-pulse' 
                            : 'text-foreground/80'}
                    >
                        {token}{' '}
                    </span>
                ))}
            </div>
        );
    };

    const handleExportPDF = () => {
        const doc = new jsPDF();
        doc.setFont("helvetica", "bold");
        doc.setFontSize(22);
        doc.setTextColor(6, 182, 212);
        doc.text("Plagiarism Audit Report", 20, 20);

        doc.setFont("helvetica", "normal");
        doc.setFontSize(10);
        doc.setTextColor(100);
        doc.text(`Generated by: PlagDetect.ai`, 20, 30);
        doc.text(`Date: ${new Date().toLocaleString()}`, 20, 35);

        doc.setFontSize(14);
        doc.setTextColor(0);
        doc.text(`Similarity Score: ${score.toFixed(1)}%`, 20, 50);

        doc.setFontSize(12);
        doc.text("Detected Matches:", 20, 65);

        let yPos = 75;
        if (matches.length === 0) {
            doc.setFontSize(10);
            doc.text("No significant plagiarism detected.", 20, yPos);
        } else {
            doc.setFontSize(10);
            matches.forEach((phrase, index) => {
                if (yPos > 270) { doc.addPage(); yPos = 20; }
                const matchTitle = `Match ${index + 1}:`;
                const splitContent = doc.splitTextToSize(`"${phrase}"`, 160);
                doc.setFont("helvetica", "bold");
                doc.text(matchTitle, 20, yPos);
                yPos += 6;
                doc.setFont("helvetica", "normal");
                doc.text(splitContent, 20, yPos);
                yPos += (splitContent.length * 6) + 6;
            });
        }
        doc.save("plagiarism-report.pdf");
    };

    const threatLevel = score > 70 ? 'Critical' : score > 40 ? 'High' : score > 20 ? 'Medium' : 'Low';
    const threatColor = score > 70 ? 'text-red-500' : score > 40 ? 'text-orange-500' : score > 20 ? 'text-yellow-500' : 'text-green-500';

    return (
        <motion.div
            id="results-section"
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            className="space-y-8"
        >
            {/* Threat Level Banner */}
            <motion.div
                initial={{ opacity: 0, y: -20 }}
                animate={{ opacity: 1, y: 0 }}
                className={`glass-card p-4 border-l-4 ${score > 50 ? 'border-red-500' : 'border-primary'}`}
            >
                <div className="flex items-center justify-between">
                    <div className="flex items-center gap-3">
                        <Shield className={threatColor} size={24} />
                        <div>
                            <h3 className="text-sm font-bold text-muted-foreground uppercase tracking-wider">Threat Level</h3>
                            <p className={`text-2xl font-black ${threatColor}`}>{threatLevel}</p>
                        </div>
                    </div>
                    <div className="text-right">
                        <p className="text-xs text-muted-foreground uppercase tracking-wider">Confidence</p>
                        <p className="text-xl font-bold text-foreground">{(100 - (score * 0.1)).toFixed(1)}%</p>
                    </div>
                </div>
            </motion.div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">

                {/* Score Card */}
                <div className="glass-card p-6 flex items-center gap-6 relative overflow-hidden group">
                    <div className="absolute inset-0 bg-gradient-to-br from-primary/10 to-accent/10 opacity-0 group-hover:opacity-100 transition-opacity duration-500"></div>
                    <div className="flex-1 z-10">
                        <h3 className="text-xs font-bold text-muted-foreground mb-2 uppercase tracking-wider flex items-center gap-2">
                            <span className="w-2 h-2 bg-primary rounded-full animate-pulse"></span>
                            Similarity Score
                        </h3>
                        <span className="text-5xl font-black text-foreground">{score.toFixed(1)}<span className="text-2xl text-primary">%</span></span>
                    </div>
                    <div className="w-24 h-24 relative z-10">
                        <Doughnut data={chartData} options={chartOptions} />
                        <div className="absolute inset-0 flex items-center justify-center">
                            {score > 50 ? <AlertTriangle size={20} className="text-red-500" /> : <CheckCircle size={20} className="text-primary" />}
                        </div>
                    </div>
                    <div className="absolute -right-8 -bottom-8 w-32 h-32 bg-primary/10 rounded-full blur-3xl"></div>
                </div>

                {/* Time Card */}
                <div className="glass-card p-6 flex flex-col justify-center relative overflow-hidden group">
                    <div className="absolute inset-0 bg-gradient-to-br from-blue-500/5 to-cyan-500/5 opacity-0 group-hover:opacity-100 transition-opacity duration-500"></div>
                    <div className="flex items-center gap-3 mb-3 z-10">
                        <div className="p-2.5 bg-blue-500/10 text-blue-400 rounded-xl border border-blue-500/20">
                            <Clock size={20} />
                        </div>
                        <h3 className="text-xs font-bold text-muted-foreground uppercase tracking-wider">Analysis Time</h3>
                    </div>
                    <span className="text-4xl font-black text-foreground z-10">{timeTaken}<span className="text-lg text-blue-400">ms</span></span>
                    <div className="absolute -right-8 -top-8 w-32 h-32 bg-blue-500/10 rounded-full blur-3xl"></div>
                </div>

                {/* Match Count Card */}
                <div className="glass-card p-6 flex flex-col justify-center relative overflow-hidden group">
                    <div className="absolute inset-0 bg-gradient-to-br from-orange-500/5 to-amber-500/5 opacity-0 group-hover:opacity-100 transition-opacity duration-500"></div>
                    <div className="flex items-center gap-3 mb-3 z-10">
                        <div className="p-2.5 bg-orange-500/10 text-orange-400 rounded-xl border border-orange-500/20">
                            <Layers size={20} />
                        </div>
                        <h3 className="text-xs font-bold text-muted-foreground uppercase tracking-wider">Matches Found</h3>
                    </div>
                    <span className="text-4xl font-black text-foreground z-10">{matches.length} <span className="text-base font-normal text-orange-400">zones</span></span>
                    <div className="absolute -right-8 -bottom-8 w-32 h-32 bg-orange-500/10 rounded-full blur-3xl"></div>
                </div>
            </div>

            {/* Diff Viewer */}
            <div className="glass-card p-8 relative overflow-hidden">
                <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-transparent via-primary to-transparent"></div>
                <div className="flex justify-between items-center mb-6">
                    <h3 className="text-lg font-black text-foreground flex items-center gap-3">
                        <div className="p-2 bg-primary/10 rounded-lg">
                            <FileText size={20} className="text-primary" />
                        </div>
                        Detailed Comparison
                    </h3>
                    <button
                        onClick={handleExportPDF}
                        className="text-sm font-bold text-muted-foreground hover:text-primary transition-all flex items-center gap-2 px-4 py-2.5 rounded-lg hover:bg-secondary border border-transparent hover:border-primary/20 active:scale-95"
                    >
                        <Download size={16} /> Export Report
                    </button>
                </div>
                {renderHighlightedContent()}
            </div>
        </motion.div>
    );
};

export default ResultsSection;
